import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { SectionHeader } from '../ui';
import { Plus, Minus } from 'lucide-react';

const faqs = [
  {
    question: "How does DYNA reduce sell pressure compared to traditional farming?",
    answer: "Unlike standard AMM farms that emit inflationary rewards with no lockup, DYNA forces a time-weighted commitment. Rewards are distributed logarithmically based on lock duration. Early unstaking incurs heavy slash penalties which are redistributed to honest actors, economically disincentivizing dumping."
  },
  {
    question: "What happens to the fees generated by the protocol?",
    answer: "100% of protocol fees generated from the internal DEX module and cross-chain bridging are programmatically routed back. 60% buys back and burns DYNA, 30% is added to the LP Staking rewards pool, and 10% funds the decentralized treasury."
  },
  {
    question: "Are the smart contracts audited?",
    answer: "Security is non-negotiable. The DYNA v2 core contracts have undergone redundant audits by leading tier-1 security firms (Reports available in the Documentation). Furthermore, we maintain a permanent $1M bug bounty program on Immunefi."
  },
  {
    question: "How do I participate in Protocol Governance?",
    answer: "Governance requires veDYNA (Vote-Escrowed DYNA), obtained by locking your tokens. The longer your lock period (up to 4 years), the greater your voting power and yield boost, ensuring decision-making is controlled by those with long-term skin in the game."
  }
];

export const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="py-32 bg-brand-bg-secondary relative border-y border-brand-border/30">
      <div className="container mx-auto px-6">
        <div className="grid lg:grid-cols-12 gap-12">
          <div className="lg:col-span-5">
            <div className="sticky top-32">
              <SectionHeader 
                badge="KNOWLEDGE BASE"
                title="Protocol Intel"
                subtitle="Classified information on the operational mechanics of the DYNA ecosystem."
              />
              
              <div className="mt-8 hidden lg:block">
                 <div className="w-48 h-48 border border-brand-border/50 rounded-full flex items-center justify-center relative animate-[spin_20s_linear_infinite]">
                   <div className="absolute inset-0 border-t border-r border-brand-accent-base/50 rounded-full animate-[spin_10s_linear_infinite]" style={{ animationDirection: 'reverse' }} />
                   <div className="w-1/2 h-[1px] bg-brand-border absolute top-1/2 left-1/2 origin-left rotate-45" />
                   <div className="w-1/2 h-[1px] bg-brand-border absolute top-1/2 left-1/2 origin-left rotate-[-45deg]" />
                   <div className="text-center font-mono text-[10px] text-brand-text-3">
                     QUERY<br/>ENGINE
                   </div>
                 </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-7 space-y-4">
            {faqs.map((faq, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className={`border transition-colors duration-300 clip-edges ${openIndex === i ? 'border-brand-accent-base/50 bg-brand-surface-1' : 'border-brand-border bg-brand-bg-primary/50'}`}
              >
                <button
                  onClick={() => setOpenIndex(openIndex === i ? null : i)}
                  className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
                >
                  <span className={`font-display text-lg tracking-wide transition-colors ${openIndex === i ? 'text-brand-accent-base' : 'text-brand-text-1'}`}>
                    <span className="font-mono text-xs mr-4 opacity-50">0{i + 1}</span>
                    {faq.question}
                  </span>
                  <span className="text-brand-text-3 flex-shrink-0 ml-4">
                    {openIndex === i ? <Minus className="w-5 h-5 text-brand-accent-base" /> : <Plus className="w-5 h-5" />}
                  </span>
                </button>
                
                <AnimatePresence>
                  {openIndex === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="p-6 pt-0 text-brand-text-3 font-sans leading-relaxed border-t border-brand-border/30 mt-2 mx-6">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
